#!/usr/bin/env sh

# nets profile

# cause this profile to be matched in the absence of other matching criteria
# DEFAULT=true
# name of Mac OS X Network Location
LOCATION="Automatic"
# 
# 
# name of Mac OS X VPN profile
VPN="Work L2TP"
# 
# 
# command line arguments to feed 'ssh' to invoke ssh tunnel
SSH="ssh -f -N -C -c blowfish-cbc -D 1080 user@proxyhost.example.com -L 5000/localhost/5000"
# 
# 
# matches the MAC address of any host on the Layer 2 network
MACADDR="aa:bb:cc:dd:ee"
# 
# 
# Wireless network ID to match
SSID="Linksys"
# 
# 
# Use growl notification
GROWL=true

# added password entry
vpn_connect() {
  if [ -n "$1" ]; then
    /usr/bin/env osascript >/dev/null <<EOF
tell application "System Events"
  tell current location of network preferences
    set VPNservice to service "$1"
    if exists VPNservice then connect VPNservice
    delay 1
    repeat while (current configuration of VPNservice is not connected)
      keystroke "vpnpassword" & return
      delay 1
    end repeat
  end tell
end tell
EOF
  fi
}
